- remove cvs changelog.
Changed files:
    mkxauth -> 1.2

diff --git a/mkxauth b/mkxauth
--- a/mkxauth
+++ b/mkxauth
@@ -4,30 +4,6 @@
 # formerly 'newcookie' script; modified 18-Jul-1996 jim knoble
 #
 ########################################################################
-# $Log$
-# Revision 1.7  1996/10/23 21:34:23  jmknoble
-# take path of least surprise if no command specified;
-# if hostnames specified with -c, don't assume local host.
-#
-# Revision 1.6  1996/10/02 20:34:12  jmknoble
-# updated help text again
-#
-# Revision 1.5  1996/10/02 20:10:03  jmknoble
-# updated help text
-#
-# Revision 1.4  1996/10/02 20:03:26  jmknoble
-# fixed quoting problem in key generation
-#
-# Revision 1.3  1996/08/20 16:31:30  jmknoble
-# refined random key generation (using mcookie if available)
-#
-# Revision 1.2  1996/08/20 15:49:33  jmknoble
-# replaced key generation using perl with method using md5sum
-#
-# Revision 1.1  1996/08/05 16:40:20  jmknoble
-# Initial revision
-#
-########################################################################
 
 #set -x
 
@@ -60,70 +36,70 @@ srcusr=''
 ########################################################################
 # help message
 function prthlp() {
-    echo ""
-    echo "  usage:  $0 [-q] [-u <login>] -m <login>"
-    echo "          $0 [-q] [-u <login>] -f <host>"
-    echo "          $0 [-q] [-u <login>] -r <host> [-l <login>]"
-    echo "          $0 [-q] [-u <login>] -z <host> [-l <login>]"
-    echo "          $0 [-q] [-u <login>] -c [<host> [<host> ... ]]"
-    echo ""
-    echo "  create or update an Xauthority database containing authentication"
-    echo "  keys for the current user or a specified user on the local host."
-    echo ""
-    echo "  commands:"
-    echo ""
-    echo "  -m <login>    merge the Xauthority database from local user <login>"
-    echo "                (if readable) with the target .Xauthority"
-    echo ""
-    echo "  -f <host>     merge a remote Xauthority database with the target"
-    echo "                .Xauthority, using ncftp"
-    echo ""
-    echo "  -r <host>     merge a remote Xauthority database with the target"
-    echo "                .Xauthority, using rsh"
-    echo ""
-    echo "  -z <host>     merge a remote Xauthority database with the target"
-    echo "                .Xauthority, using rsh and gzip"
-    echo ""
-    echo "  -c <host>...  create a local Xauthority database, or add keys to an"
-    echo "                existing one, for all hosts listed (uses md5sum).  if"
-    echo "                no hosts are listed, assume the local host."
-    echo ""
-    echo "  options:"
-    echo ""
-    echo "  -q            quiet operation"
-    echo ""
-    echo "  -u <login>    create/merge .Xauthority for user <login>"
-    echo ""
-    echo "  -l <login>    for '-f', '-r' and '-z' modes, use <login> for the"
-    echo "                remote login"
-    echo ""
+	echo ""
+	echo "  usage:  $0 [-q] [-u <login>] -m <login>"
+	echo "          $0 [-q] [-u <login>] -f <host>"
+	echo "          $0 [-q] [-u <login>] -r <host> [-l <login>]"
+	echo "          $0 [-q] [-u <login>] -z <host> [-l <login>]"
+	echo "          $0 [-q] [-u <login>] -c [<host> [<host> ... ]]"
+	echo ""
+	echo "  create or update an Xauthority database containing authentication"
+	echo "  keys for the current user or a specified user on the local host."
+	echo ""
+	echo "  commands:"
+	echo ""
+	echo "  -m <login>    merge the Xauthority database from local user <login>"
+	echo "                (if readable) with the target .Xauthority"
+	echo ""
+	echo "  -f <host>     merge a remote Xauthority database with the target"
+	echo "                .Xauthority, using ncftp"
+	echo ""
+	echo "  -r <host>     merge a remote Xauthority database with the target"
+	echo "                .Xauthority, using rsh"
+	echo ""
+	echo "  -z <host>     merge a remote Xauthority database with the target"
+	echo "                .Xauthority, using rsh and gzip"
+	echo ""
+	echo "  -c <host>...  create a local Xauthority database, or add keys to an"
+	echo "                existing one, for all hosts listed (uses md5sum).  if"
+	echo "                no hosts are listed, assume the local host."
+	echo ""
+	echo "  options:"
+	echo ""
+	echo "  -q            quiet operation"
+	echo ""
+	echo "  -u <login>    create/merge .Xauthority for user <login>"
+	echo ""
+	echo "  -l <login>    for '-f', '-r' and '-z' modes, use <login> for the"
+	echo "                remote login"
+	echo ""
 
-    exit 0
+	exit 0
 }
 
 # check that current user is root
 function chkroot() {
     if [ `whoami` != root ]; then
-        echo "sorry---you need to be root" "$*"
-        exit 1
+    	echo "sorry---you need to be root" "$*"
+	exit 1
     fi
 }
 
 # write a message to stdout iff verbose mode on
 function msg() {
-    if [ -z "$opt_vrbopr" ]; then
-        echo "$@"
-    fi
+	if [ -z "$opt_vrbopr" ]; then
+		echo "$@"
+	fi
 }
 
 # check that a command exists
 function chkcmdexs() {
-    for i in $*; do
-        if [ -z `type -p $i` ]; then
-            echo "`basename $0`: error: can't find command '$i'"
-            exit 1
-        fi
-    done
+	for i in $*; do
+		if [ -z `type -p $i` ]; then
+			echo "`basename $0`: error: can't find command '$i'"
+			exit 1
+		fi
+	done
 }
 
 # check that a file exists, and create it if it doesn't
@@ -142,42 +118,42 @@ function chkfilexs() {
 
 # check if a file is readable
 function redabl() {
-    local srcfil=$1
-    if [ -r "$srcfil" ]; then
-        sts=0
-    else
-        echo "`basename $0`: error: cannot read file $srcfil"
-        sts=1
-    fi
-    return $sts
+	local srcfil=$1
+	if [ -r "$srcfil" ]; then
+		sts=0
+	else
+		echo "`basename $0`: error: cannot read file $srcfil"
+		sts=1
+	fi
+	return $sts
 }
 
 # check if a file is writable
 function wrtabl() {
-    local dstfil=$1
-    if [ -w "$dstfil" ]; then
-        sts=0
-    else
-        echo "`basename $0`: error: cannot write to file $dstfil"
-        sts=1
-    fi
-    return $sts
+	local dstfil=$1
+	if [ -w "$dstfil" ]; then
+		sts=0
+	else
+		echo "`basename $0`: error: cannot write to file $dstfil"
+		sts=1
+	fi
+	return $sts
 }
 
 # set the correct ownership for a file
 function givusr() {
-    local lststs=$1
-    local usrnam=$2
-    local dstfil=$3
-    if [ $lststs = 0 ]; then
-        chown $usrnam.$usrnam $dstfil
-        sts=0
-    else
-        msg ""
-        echo "`basename $0`: error writing to file $dstfil"
-        sts=1
-    fi
-    return $sts
+	local lststs=$1
+	local usrnam=$2
+	local dstfil=$3
+	if [ $lststs = 0 ]; then
+		chown $usrnam.$usrnam $dstfil
+		sts=0
+	else
+		msg ""
+		echo "`basename $0`: error writing to file $dstfil"
+		sts=1
+	fi
+	return $sts
 }
 
 ########################################################################
@@ -234,7 +210,7 @@ while [ "$*" ]; do
             shift
             ;;
         -*)
-            echo "`basename $0`: invalid option '$1'"
+        	echo "`basename $0`: invalid option '$1'"
             shift
             prthlp
             ;;
@@ -351,7 +327,7 @@ case $xauth_mode in
         ;;
     *)
         # something's hosed
-        echo "oops!  xauth_mode = '$xauth_mode' - this shouldn't happen."
+    	echo "oops!  xauth_mode = '$xauth_mode' - this shouldn't happen."
         sts=1
         ;;
 esac
@@ -374,4 +350,3 @@ case $xauth_mode in
 esac
 
 exit $sts
-
